
### Employees API

# Create a new employee
POST http://127.0.0.1:8081/api/employees
Content-Type: application/json

{
  "login": "uzb_employee",
  "password": "uz_123456",
  "activated": true,
  "department": {
    "name": "HR"
  },
  "employeeStatus": "ACTIVE",
  "employeePosition": "EMPLOYEE",
  "salary": 40000,
  "passport": {
    "firstName": "Komil",
    "lastName": "Misirov",
    "middleName": "Adilovich",
    "birthday": "1995-10-01T00:00:00Z",
    "address": "Beruniy 12",
    "passportSerial": "AQ",
    "passportNumber": "987654321",
    "JSHSHIR": "23456789012345",
    "nation": "Nation"
  }
}
###
# Get all employees
GET http://127.0.0.1:8081/api/employees
Authorization: Basic "director_admin" "123456"
###
# Update an employee
PUT http://127.0.0.1:8081/api/employees/{id}
Authorization: Basic "director_admin" "123456"
Content-Type: application/json

{
  "salary": 45000
}
###
# Delete an employee
DELETE http://127.0.0.1:8081/api/employees/{id}
Authorization: Basic "director_admin" "123456"

### Clients API

# Create a new client
POST http://127.0.0.1:8081/api/clients
Authorization: Basic "director_admin" "123456"
Content-Type: application/json

{
  "archive": false,
  "passport": {
    "firstName": "Olim",
    "lastName": "Abdullayev",
    "middleName": "Qodirovich",
    "birthday": "1990-01-01T00:00:00Z",
    "address": "123 Main St",
    "passportSerial": "AB123",
    "passportNumber": "123456789",
    "JSHSHIR": "12345678901234",
    "nation": "Nation"
  }
}
###
# Get all clients
GET http://127.0.0.1:8081/api/clients
Authorization: Basic "director_admin" "123456"
###
# Update a client
PUT http://127.0.0.1:8081/api/clients/{id}
Authorization: Basic "director_admin" "123456"
Content-Type: application/json

{
"archive": true
}
###
# Delete a client
DELETE http://127.0.0.1:8081/api/clients/{id}


### Sales API

# Create a new sale
POST http://127.0.0.1:8081/api/sales
Authorization: Basic "director_admin" "123456"
Content-Type: application/json

{
  "amount": 1000.0,
  "duration": "2023-10-01T00:00:00Z",
  "adsType": "ONLINE",
  "beginDate": "2023-10-01T00:00:00Z",
  "employee": {
    "id": 1
  }
}
###
# Get all sales
GET http://127.0.0.1:8081/api/sales
Authorization: Basic "director_admin" "123456"
###
# Update a sale
PUT http://127.0.0.1:8081/api/sales/{id}
Authorization: Basic "director_admin" "123456"
Content-Type: application/json

{
"amount": 1200.0
}
###
# Delete a sale
DELETE http://127.0.0.1:8081/api/sales/{id}
Authorization: Basic "director_admin" "123456"

### Statistics employee API
# @no-cookie-jar
GET http://127.0.0.1:8081/api/statistics/employee
Authorization: Basic "director_admin" "123456"

### Statistics employee by age
GET http://127.0.0.1:8081/api/statistics/employee/age/24
Authorization: Basic "director_admin" "123456"

### Statistics employee by salary
GET http://127.0.0.1:8081/api/statistics/employee/salary
Authorization: Basic "director_admin" "123456"

### Statistics by client/daily-registered
GET http://127.0.0.1:8081/api/statistics/clients/daily-registered
Authorization: Basic "director_admin" "123456"




